# These docker image are used to config that the dynamic build works locally on linux
# Use a slim base image
FROM debian:bullseye-slim

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        wget \
        pkg-config \
        libboost-all-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
    && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Copy the whole project
#COPY . .

## Create build directory and compile
#ENTRYPOINT ["docker/build_dynamic.sh"]